GET http://localhost:8080/admin/categories HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/admin/category/add HTTP/1.1
Content-Type: application/json

{
    "categoryName": "Test Name",
    "categoryDescription": "Test Desc"

}

###